version: '3.7'

services: 
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - "31011:9000"
        volumes: 
            - ./source:/usr/src/app          