version: '3.7'

services: 
    web:
        image: php:5.6-apache
        stdin_open: true
        tty: true

        ports: 
            - '30073:80'
        volumes: 
            - ./source:/var/www/html
            - ./logs:/var/log/apache2
            - ./flag:/flag
